name: Trigger auto deployment for dominion-server

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/dominion-server-AutoDeployTrigger-bd4353b9-d3d4-4e93-bf0d-2b1c727fb838.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.DOMINIONSERVER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DOMINIONSERVER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DOMINIONSERVER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          acrName: dominion
          appSourcePath: ${{ github.workspace }}/Dominion.Backend
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUsername: ${{ secrets.DOMINIONSERVER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DOMINIONSERVER_REGISTRY_PASSWORD }}
          containerAppName: dominion-server
          resourceGroup: dominion-server
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


